enable-magisk-update = true
parallel-jobs = 1
remove-rv-integrations-checks = true

# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use [rvmm-config-gen](https://j-hc.github.io/rvmm-config-gen/) to generate a config

[nyatube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Custom branding' 'Shorts autoplay' 'Enable debugging' 'Disable haptic feedback' 'Loop video'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
